export declare function produceCorrelationId(event: any, context: any): string;
export declare function produceRegion(context: any): string;
export declare function produceRuntime(): string;
export declare function produceFunctionName(context: any): string;
export declare function produceFunctionMemorySize(context: any): string;
export declare function produceFunctionVersion(context: any): string;
export declare function produceRoute(event: any): string;
export declare function produceUser(event: any): string;
export declare function produceStage(event: any): string;
export declare function produceViewerCountry(event: any): string;
export declare function produceAccountId(event: any): string;
export declare function produceTimestampRequest(event: any): string;
