name: main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [18.x]
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm audit fix

      - name: Test
        run: npm test

      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}
          #test_format: todo
          #test_framework: todo
          test_path: coverage/
          coverage_format: LCOV/TXT
          coverage_path: coverage/